import { describe, expect, it } from 'vitest'
import {
  ciRules,
  conventions,
  envRule,
  filterPattern,
  ormRule,
  packageManagerRule,
  runtimeRule,
  styleRule,
  testingRule,
  verifyRule,
  workspaceRule,
} from '../../src/agent/conventions.ts'
import { GENERATED_MARKER, generatedHeader, renderAgentContext, renderAgentFiles } from '../../src/agent/index.ts'
import { filterByConfidence } from '../../src/core/confidence.ts'
import type { ScanResult } from '../../src/types.ts'
import { makeResult, sampleScanResult } from '../factories.ts'
import { copyFixture, SECRET_SENTINEL, scanDir } from '../helpers.ts'
import { hostile, markdownProblems, withoutCodeSpans } from '../output/markdown-assertions.ts'
import { largeScanResult } from '../output/synthetic.ts'

const FILE_NAMES = [
  'overview.md',
  'architecture.md',
  'commands.md',
  'environment.md',
  'services.md',
  'routes.md',
  'development.md',
  'agent-context.md',
]

const HEADER = '<!-- Generated by RepoLens v1.2.3. Review before committing. Regenerate with: repolens agent init -->'

function fileMap(result: ScanResult): Map<string, string> {
  return new Map(renderAgentFiles(result).map((file) => [file.name, file.content]))
}

function lineCount(content: string): number {
  return content.trimEnd().split('\n').length
}

/** Lines of one "## Title" section, without the heading and blank lines. */
function sectionLines(content: string, title: string): string[] {
  const lines = content.split('\n')
  const start = lines.indexOf(`## ${title}`)
  if (start === -1) return []
  const rest = lines.slice(start + 1)
  const end = rest.findIndex((line) => line.startsWith('## ') || line === '---')
  return (end === -1 ? rest : rest.slice(0, end)).filter((line) => line !== '')
}

describe('renderAgentFiles', () => {
  it('returns the documented files in a stable order', () => {
    expect(renderAgentFiles(sampleScanResult()).map((file) => file.name)).toEqual(FILE_NAMES)
  })

  it.each(FILE_NAMES)('%s starts with the generated-file header', (name) => {
    const content = fileMap(sampleScanResult()).get(name) ?? ''
    expect(content.startsWith(GENERATED_MARKER)).toBe(true)
    expect(content.split('\n')[0]).toBe(HEADER)
  })

  it.each(FILE_NAMES)('%s matches its snapshot', async (name) => {
    await expect(fileMap(sampleScanResult()).get(name)).toMatchFileSnapshot(`__snapshots__/${name}`)
  })

  it.each([
    ['sample', sampleScanResult],
    ['large result', () => largeScanResult()],
    ['empty result', () => makeResult()],
  ])('every file is well-formed Markdown: %s', (_name, build) => {
    for (const file of renderAgentFiles(build())) {
      expect(markdownProblems(file.content), file.name).toEqual([])
    }
  })

  it('still writes every file, with a title, for an empty result', () => {
    for (const file of renderAgentFiles(makeResult())) {
      expect(file.content.split('\n')[0]).toContain(GENERATED_MARKER)
      expect(file.content).toMatch(/^# .+: project$/m)
      expect(lineCount(file.content)).toBeLessThan(15)
    }
  })

  it('is deterministic', () => {
    expect(renderAgentFiles(sampleScanResult())).toEqual(renderAgentFiles(sampleScanResult()))
  })

  it('caps routes.md and says how many routes were left out', () => {
    const routes = fileMap(largeScanResult()).get('routes.md') ?? ''
    expect(routes).toContain('400 API routes and 100 pages')
    expect(routes).toContain('_… and 300 more routes._')
    expect(routes.split('\n').filter((line) => /^\| (?:GET|POST|PUT|PATCH|DELETE) \|/.test(line))).toHaveLength(200)
  })

  it('documents variable names and where they are documented, never values', () => {
    const environment = fileMap(sampleScanResult()).get('environment.md') ?? ''
    expect(environment).toContain('| `DATABASE_URL` | ✓ | ✓ | ✓ | points at postgres, port 5432 | `.env.example` |')
    expect(environment).toContain('| `STRIPE_SECRET_KEY` | ✗ | ✗ | ✓ | undocumented; not set locally; secret | – |')
    expect(environment).toContain('A local `.env` exists.')
  })

  it('explains how to create .env when only an example exists', () => {
    const result = sampleScanResult()
    result.environment.files = result.environment.files.filter((file) => file.kind === 'example')
    const environment = fileMap(result).get('environment.md') ?? ''
    expect(environment).toContain('1. `cp .env.example .env` — create your local environment file.')
    expect(renderAgentContext(result)).toContain('Create the local env file with `cp .env.example .env`.')
  })

  it('lists setup, checks, CI and doctor findings in development.md', () => {
    const development = fileMap(sampleScanResult()).get('development.md') ?? ''
    expect(sectionLines(development, 'Setup')).toEqual([
      '1. `pnpm db:up` — start local services',
      '2. `pnpm install` — install dependencies',
      '3. `pnpm dev` — start the development server',
    ])
    expect(sectionLines(development, 'Before finishing a change')).toEqual([
      'Run these and make sure they pass:',
      '- `pnpm lint`',
      '- `pnpm test`',
      'If the change affects the build, also run `pnpm build`.',
    ])
    expect(development).toContain('`ci.yml` (GitHub Actions) on push, pull_request: lint, typecheck, test, build')
    expect(development).toContain('- **TRACKED_ENV_FILE** — .env is tracked by Git')
  })

  it('never contains secret values, even when committed text includes them', () => {
    const result = sampleScanResult()
    result.scripts.scripts.push({
      name: 'deploy',
      command: 'API_TOKEN=hunter2 deploy --password s3cret postgres://admin:pw@db/app',
      run: 'API_TOKEN=hunter2 pnpm deploy',
      source: 'package.json',
      package: '.',
      category: 'deploy',
    })
    for (const file of renderAgentFiles(result)) {
      for (const secret of ['hunter2', 's3cret', 'admin:pw']) expect(file.content, file.name).not.toContain(secret)
    }
  })

  it('does not name any particular agent vendor', () => {
    for (const file of renderAgentFiles(sampleScanResult())) {
      expect(file.content).not.toMatch(/claude|codex|cursor|copilot|openai|anthropic/i)
    }
  })

  it.each(['monorepo', 'docker-project', 'broken-env', 'go-api', 'plain-repo', 'bun-app'])(
    '%s fixture: well-formed, no secret values and no absolute paths',
    async (fixture) => {
      const dir = await copyFixture(fixture)
      const result = filterByConfidence(await scanDir(dir))
      for (const file of renderAgentFiles(result)) {
        expect(file.content, file.name).not.toContain(SECRET_SENTINEL)
        expect(file.content, file.name).not.toContain(dir)
        expect(markdownProblems(file.content), file.name).toEqual([])
      }
    },
  )
})

describe('renderAgentContext', () => {
  it('points at companion files only when they are written alongside it', () => {
    const result = sampleScanResult()
    expect(renderAgentContext(result)).toContain('(see `routes.md`)')
    const standalone = renderAgentContext(result, { companionFiles: false })
    expect(standalone).not.toMatch(/see `\w+\.md`/)
    expect(standalone).toContain('(run `repolens agent init` for the full list)')
  })

  it('is the agent-context.md file', () => {
    expect(renderAgentContext(sampleScanResult())).toBe(fileMap(sampleScanResult()).get('agent-context.md'))
  })

  it('has the documented structure', () => {
    const context = renderAgentContext(sampleScanResult())
    const lines = context.split('\n')
    expect(lines[0]).toBe(HEADER)
    expect(lines[2]).toBe('# Agent context: acme-api')
    expect(lines[4]).toBe('_Static analysis only; verify before relying on it._')
    expect(lines.filter((line) => line.startsWith('## '))).toEqual([
      '## Project',
      '## Commands',
      '## Conventions',
      '## Structure',
      '## Services & environment',
      '## API routes',
      '## Potential issues',
    ])
    // The first-line marker names RepoLens; a footer saying it again is gone.
    expect(context.match(/generated by repolens/gi)).toHaveLength(1)
    expect(context).not.toContain('\n---\n')
  })

  it('lists only the commands that exist, with exact run strings', () => {
    expect(sectionLines(renderAgentContext(sampleScanResult()), 'Commands')).toEqual([
      '- Install: `pnpm install`',
      '- Dev: `pnpm dev`',
      '- Test: `pnpm test`',
      '- Lint: `pnpm lint`',
      '- Build: `pnpm build`',
    ])
  })

  it('lists error and warning diagnostics, not infos', () => {
    const issues = sectionLines(renderAgentContext(sampleScanResult()), 'Potential issues')
    expect(issues).toEqual([
      '- `TRACKED_ENV_FILE` (error): .env is tracked by Git. Fix: Run `git rm --cached .env` and add .env to .gitignore.',
      '- `ENV_UNDOCUMENTED` (warning): STRIPE_SECRET_KEY is used in code but missing from .env.example. Fix: Add STRIPE_SECRET_KEY= to .env.example.',
      '- `NODE_VERSION_CONFLICT` (warning): Node.js versions disagree: .nvmrc pins 22, Dockerfile uses 20. Fix: Use the same major version everywhere (22).',
    ])
  })

  it('groups environment variable names', () => {
    const lines = sectionLines(renderAgentContext(sampleScanResult()), 'Services & environment')
    expect(lines).toEqual([
      '- Services (`docker-compose.yml`): `postgres` (5432), `redis` (6379), `minio` (9000, 9001). Start: `pnpm db:up`',
      '- Documented variables (`.env.example`): `API_URL`, `DATABASE_URL`, `LEGACY_FLAG`, `REDIS_URL`',
      '- Used in code but undocumented: `STRIPE_SECRET_KEY`',
    ])
  })

  it('stays under 150 lines for the sample', () => {
    expect(lineCount(renderAgentContext(sampleScanResult()))).toBeLessThan(150)
  })

  it('stays under 200 lines for a large repository (500 routes, 200 variables)', () => {
    const context = renderAgentContext(largeScanResult({ routes: 500, variables: 200 }))
    expect(lineCount(context)).toBeLessThan(200)
    expect(sectionLines(context, 'API routes').filter((line) => line.startsWith('- `'))).toHaveLength(25)
    expect(context).toContain('- … and 375 more API routes (see `routes.md`)')
    expect(context).toContain('- Plus 100 pages (see `routes.md`)')
    expect(context).toContain('more (see `environment.md`)')
    expect(context).toContain('- … and 40 more packages (see `architecture.md`)')
    expect(context).toMatch(/- … and \d+ more \(run `repolens doctor`\)/)
  })

  it('says so when there is nothing to report', () => {
    const context = renderAgentContext(makeResult())
    expect(context).toContain('RepoLens found nothing to report in this directory.')
    expect(context).not.toContain('## ')
  })
})

describe('generatedHeader', () => {
  it('cannot be used to close the HTML comment early', () => {
    const header = generatedHeader('1.0.0 --> <script>')
    expect(header.startsWith(GENERATED_MARKER)).toBe(true)
    expect(header.match(/-->/g)).toHaveLength(1)
    expect(header).toBe(
      '<!-- Generated by RepoLens v1.0.0-script. Review before committing. Regenerate with: repolens agent init -->',
    )
  })
})

describe('conventions', () => {
  it('derives every rule from the sample data', () => {
    expect(conventions(sampleScanResult())).toEqual([
      'Use pnpm (packageManager field in package.json); do not use npm or yarn.',
      'Use Node.js 22 (`.nvmrc`; other files disagree, see `NODE_VERSION_CONFLICT`) and Go 1.25 (`services/billing/go.mod` go directive).',
      'Run `pnpm lint` and `pnpm test` before finishing a change.',
      'Monorepo (pnpm workspaces, Turborepo): packages live in `apps/*` and `packages/*`; run a package script with `pnpm --filter <package> <script>` (e.g. `pnpm --filter @acme/web dev`).',
      'Never commit `.env` files or paste their values; document new variables in `.env.example`.',
      'CI (GitHub Actions `ci.yml`) runs: lint, typecheck, test, build.',
      'Code style is enforced by Biome (`biome.json`).',
      'Tests use Vitest; end-to-end tests use Playwright.',
      'Database access goes through Prisma (`apps/api/prisma/schema.prisma`).',
    ])
  })

  it('produces no rules without evidence', () => {
    expect(conventions(makeResult())).toEqual([])
  })

  it('names the lockfile when the package manager is not declared', () => {
    const result = makeResult({
      packageManagers: {
        primary: { id: 'npm', name: 'npm', lockfiles: ['package-lock.json'], declared: false, evidence: [] },
        detected: [],
      },
    })
    expect(packageManagerRule(result)).toBe('Use npm (lockfile `package-lock.json`); do not use pnpm or yarn.')
  })

  it('has no package manager rule for non-JavaScript managers', () => {
    const result = makeResult({
      packageManagers: {
        primary: { id: 'go', name: 'Go modules', lockfiles: ['go.sum'], declared: true, evidence: ['go.mod'] },
        detected: [],
      },
    })
    expect(packageManagerRule(result)).toBeNull()
  })

  it('skips runtimes without a version', () => {
    const result = makeResult({ runtimes: [{ id: 'node', name: 'Node.js', version: null, sources: [] }] })
    expect(runtimeRule(result)).toBeNull()
    const ranged = makeResult({
      runtimes: [
        {
          id: 'node',
          name: 'Node.js',
          version: '>=22',
          sources: [{ file: 'package.json', field: 'engines.node', raw: '>=22', version: '>=22', kind: 'range' }],
        },
      ],
    })
    expect(runtimeRule(ranged)).toBe('Use Node.js >=22 (`package.json` engines.node).')
  })

  it('only mentions .env files when the repository has env files', () => {
    expect(envRule(makeResult())).toBeNull()
    const localOnly = makeResult({
      environment: {
        files: [{ path: '.env', kind: 'local', variables: 1, ignored: true, tracked: false }],
        variables: [],
        usageTruncated: false,
      },
    })
    expect(envRule(localOnly)).toBe('Never commit `.env` files or paste their values.')
  })

  it('runs the checks in lint, typecheck, test order', () => {
    const result = sampleScanResult()
    result.scripts.scripts.push({
      name: 'typecheck',
      command: 'tsc --noEmit',
      run: 'pnpm typecheck',
      source: 'package.json',
      package: '.',
      category: 'typecheck',
    })
    expect(verifyRule(result)).toBe('Run `pnpm lint`, `pnpm typecheck` and `pnpm test` before finishing a change.')
  })

  it('describes workspace filtering per package manager', () => {
    expect(filterPattern('pnpm')).toBe('pnpm --filter <package> <script>')
    expect(filterPattern('yarn')).toBe('yarn workspace <package> <script>')
    expect(filterPattern('bun')).toBe('bun run --filter <package> <script>')
    expect(filterPattern('npm')).toBe('npm run <script> -w <directory>')
    expect(filterPattern('go')).toBeNull()
    const result = sampleScanResult()
    if (result.workspace) result.workspace.patterns = ['apps/*', '!apps/legacy']
    expect(workspaceRule(result)).toContain('packages live in `apps/*`;')
  })

  it('limits CI rules and ignores workflows without checks', () => {
    const result = largeScanResult()
    expect(ciRules(result)).toHaveLength(4)
    expect(ciRules(result)[3]).toBe('9 more CI workflows run checks.')
    const deployOnly = sampleScanResult()
    deployOnly.ci.workflows = [
      {
        provider: 'github-actions',
        file: '.github/workflows/deploy.yml',
        triggers: ['push'],
        jobs: [{ id: 'deploy', tasks: ['deploy'], runsOn: [] }],
      },
    ]
    expect(ciRules(deployOnly)).toEqual([])
  })

  it('describes tooling only when it exists', () => {
    const empty = makeResult()
    expect(styleRule(empty)).toBeNull()
    expect(testingRule(empty)).toBeNull()
    expect(ormRule(empty)).toBeNull()
    const e2eOnly = sampleScanResult()
    e2eOnly.testing.tools = e2eOnly.testing.tools.filter((tool) => tool.kind === 'e2e')
    expect(testingRule(e2eOnly)).toBe('End-to-end tests use Playwright.')
  })
})

describe('review regressions', () => {
  it('keeps every file well-formed when committed strings carry Markdown, HTML and escapes', () => {
    const result = { ...hostile(sampleScanResult()), tool: sampleScanResult().tool }
    for (const file of renderAgentFiles(result)) {
      expect(markdownProblems(file.content), file.name).toEqual([])
      expect(file.content.split('\n')[0], file.name).toBe(HEADER)
      expect(withoutCodeSpans(file.content), file.name).not.toMatch(/(?<!\\)<b>/)
      expect(file.content, file.name).not.toMatch(/^#{1,6} H\b/m)
    }
  })

  it("does not forbid other package managers on the strength of RepoLens's npm default", () => {
    const result = makeResult({
      packageManagers: {
        primary: {
          id: 'npm',
          name: 'npm',
          lockfiles: [],
          declared: false,
          evidence: ['package.json without a lockfile'],
        },
        detected: [],
      },
    })
    expect(packageManagerRule(result)).toBeNull()
    const pnpmWorkspace = makeResult({
      packageManagers: {
        primary: {
          id: 'pnpm',
          name: 'pnpm',
          lockfiles: [],
          declared: false,
          evidence: ['workspace file pnpm-workspace.yaml'],
        },
        detected: [],
      },
    })
    expect(packageManagerRule(pnpmWorkspace)).toBe(
      'Use pnpm (workspace file pnpm-workspace.yaml); do not use npm or yarn.',
    )
  })

  it("avoids nested parentheses with the detector's declared-manager evidence", () => {
    const result = makeResult({
      packageManagers: {
        primary: {
          id: 'yarn',
          name: 'Yarn',
          version: '4.10.3',
          lockfiles: ['yarn.lock'],
          declared: true,
          evidence: ['packageManager field in package.json (yarn@4.10.3)', 'lockfile yarn.lock'],
        },
        detected: [],
      },
    })
    expect(packageManagerRule(result)).toBe('Use Yarn (packageManager field in package.json); do not use npm or pnpm.')
  })

  it('says when the files pinning a runtime disagree', () => {
    const result = sampleScanResult()
    expect(runtimeRule(result)).toBe(
      'Use Node.js 22 (`.nvmrc`; other files disagree, see `NODE_VERSION_CONFLICT`) and Go 1.25 (`services/billing/go.mod` go directive).',
    )
    result.doctor.diagnostics = result.doctor.diagnostics.filter((d) => d.code !== 'NODE_VERSION_CONFLICT')
    expect(runtimeRule(result)).toBe('Use Node.js 22 (`.nvmrc`) and Go 1.25 (`services/billing/go.mod` go directive).')
  })

  it('never tells an agent to run the npm placeholder test script or a watcher', () => {
    const result = makeResult({
      packageManagers: {
        primary: { id: 'npm', name: 'npm', lockfiles: ['package-lock.json'], declared: false, evidence: [] },
        detected: [],
      },
      scripts: {
        runner: 'npm run',
        scripts: [
          {
            name: 'test',
            command: 'echo "Error: no test specified" && exit 1',
            run: 'npm test',
            source: 'package.json',
            package: '.',
            category: 'test',
          },
          {
            name: 'lint:watch',
            command: 'esw --watch',
            run: 'npm run lint:watch',
            source: 'package.json',
            package: '.',
            category: 'lint',
          },
        ],
      },
    })
    expect(verifyRule(result)).toBeNull()
    const context = renderAgentContext(result)
    expect(context).not.toContain('npm test')
    expect(context).not.toContain('lint:watch')
    const development = fileMap(result).get('development.md') ?? ''
    expect(development).not.toContain('Before finishing a change')
  })

  it('counts only the kinds of routes that exist in routes.md', () => {
    const result = sampleScanResult()
    result.routes.routes = result.routes.routes.filter((route) => route.kind === 'api')
    expect(fileMap(result).get('routes.md')).toContain('\n6 API routes, found by static analysis.')
    result.routes.routes = sampleScanResult().routes.routes.filter((route) => route.kind === 'page')
    expect(fileMap(result).get('routes.md')).toContain('\n2 pages, found by static analysis.')
  })

  it('keeps agent-context.md short when the description is huge and says how much structure it left out', () => {
    const result = largeScanResult()
    result.project.description = 'word '.repeat(50_000)
    const context = renderAgentContext(result)
    const projectLine = context.split('\n').find((line) => line.startsWith('- word')) ?? ''
    expect(projectLine.length).toBeLessThan(300)
    expect(projectLine).toMatch(/^- (?:word ){30,}word… Monorepo with 60 workspace packages/)
    expect(context).toContain('`dir-8/` (992 files), `dir-9/` (991 files) and 5 more')
    expect(lineCount(context)).toBeLessThan(200)
  })

  it('summarizes CI workflows beyond the limit in development.md', () => {
    const result = largeScanResult()
    const workflow = result.ci.workflows[0]
    if (!workflow) throw new Error('large result has workflows')
    result.ci.workflows = Array.from({ length: 60 }, (_, i) => ({
      ...workflow,
      file: `.github/workflows/w${String(i).padStart(2, '0')}.yml`,
    }))
    expect(fileMap(result).get('development.md')).toContain('_… and 10 more workflows._')
  })

  it('counts doctor findings in plain words, without the info items (UX-22)', () => {
    const intro = (result: ScanResult) =>
      sectionLines(fileMap(result).get('development.md') ?? '', 'Potential issues')[0] ?? ''
    expect(intro(sampleScanResult())).toBe(
      'RepoLens doctor found 1 error and 2 warnings (and 1 info note). Keep them in mind when changing the files involved.',
    )
    const one = sampleScanResult()
    one.doctor.diagnostics = one.doctor.diagnostics.filter((d) => d.code === 'ENV_UNDOCUMENTED')
    expect(intro(one)).toBe('RepoLens doctor found 1 warning. Keep it in mind when changing the files involved.')
  })

  it('never lists platform or test-only variables as undocumented in the agent context (ACC-L2)', () => {
    const result = sampleScanResult()
    const base = result.environment.variables[0]
    if (!base) throw new Error('sample has variables')
    const used = {
      ...base,
      defined: false,
      documented: false,
      used: true,
      documentedIn: [],
      definedIn: [],
      endpoints: [],
    }
    result.environment.variables.push(
      { ...used, name: 'CI' },
      { ...used, name: 'NODE_ENV' },
      { ...used, name: 'npm_lifecycle_event' },
      { ...used, name: 'TEST_ONLY_URL', testOnly: true },
    )
    const lines = sectionLines(renderAgentContext(result), 'Services & environment')
    expect(lines).toContain('- Used in code but undocumented: `STRIPE_SECRET_KEY`')
    expect(renderAgentContext(result)).not.toMatch(/`CI`|NODE_ENV|npm_lifecycle_event|TEST_ONLY_URL/)
  })

  it('never offers a destructive script as the example workspace command (ACC-L2)', () => {
    const result = sampleScanResult()
    result.scripts.scripts.unshift({
      name: 'clean',
      command: 'git clean -xdf',
      run: 'pnpm --filter @acme/api clean',
      source: 'apps/api/package.json',
      package: 'apps/api',
      category: 'other',
    })
    expect(workspaceRule(result)).toContain('(e.g. `pnpm --filter @acme/web dev`)')
    expect(renderAgentContext(result)).not.toContain('clean')
  })

  it('uses the local env file the project keeps (.env.local) in environment.md (UX-12)', () => {
    const result = sampleScanResult()
    result.environment.files = [
      { path: '.env.local', kind: 'local', variables: 3, ignored: true, tracked: false },
      { path: '.env.example', kind: 'example', variables: 4, ignored: false, tracked: true },
    ]
    const environment = fileMap(result).get('environment.md') ?? ''
    expect(environment).toContain(
      'A local `.env.local` exists. Compare it with `.env.example` when variables are added.',
    )
    expect(environment).not.toContain('Fill in the values in `.env`')
    expect(renderAgentContext(result)).not.toContain('cp .env.example')
  })

  it('removes zero-width and tag characters from every agent file (CQ4)', () => {
    const tags = String.fromCodePoint(0xe0049, 0xe0067, 0xe006e, 0xe006f, 0xe0072, 0xe0065)
    const result = sampleScanResult()
    result.project.description = `Acme${String.fromCharCode(0x200b)} storefront${tags}`
    result.environment.variables.push({
      ...(result.environment.variables[0] as ScanResult['environment']['variables'][number]),
      name: `SNEAKY${tags}_KEY`,
    })
    for (const file of renderAgentFiles(result)) {
      expect(file.content, file.name).not.toMatch(/[\u200b]|\udb40[\udc00-\udc7f]/)
    }
  })
})
