import type { DependencyKind, PackageDependencies, ScanResult } from '../types.ts'
import { compareText } from '../utils/compare.ts'
import { quickStart } from './commands.ts'
import {
  cmd,
  connections,
  DESCRIPTION_LIMIT,
  databasesTable,
  diagnosticGroups,
  dockerfilesList,
  ENV_LEGEND,
  entrypointsList,
  envFilesList,
  envTable,
  frameworksTable,
  languagesTable,
  moreLine,
  ormSummary,
  overviewRows,
  packageScriptsTable,
  packagesTable,
  pkgRef,
  projectTitle,
  ROW_LIMIT,
  routeTables,
  scriptsTable,
  servicesTable,
  startServices,
  structureList,
  toolingBlocks,
  warningMessage,
  workflowBlocks,
} from './markdown/blocks.ts'
import {
  type Block,
  bullets,
  code,
  codeList,
  details,
  document,
  inline,
  numbered,
  section,
  table,
  text,
} from './markdown/syntax.ts'
import {
  configNote,
  countSeverities,
  displayRemote,
  groupScripts,
  noteWarnings,
  severityParts,
  uncoveredWarnings,
} from './shared/facts.ts'
import { projectTypeLabel, TERMS } from './shared/labels.ts'
import { detailLine, formatNumber, joinWords, plural, safeText, truncate } from './shared/text.ts'

export interface MarkdownOptions {
  /** Include low-confidence findings and evidence. */
  verbose?: boolean
}

/** Where the "Generated by RepoLens" link points (the repository in package.json). */
export const REPOLENS_URL = 'https://github.com/Douglas-Strey/repolens-cli'

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

function overview(result: ScanResult): string | null {
  const rows = overviewRows(result, { extended: false })
  return rows.length > 0 ? section('Overview', 2, table(['Property', 'Value'], rows)) : null
}

function quickStartSection(result: ScanResult): string | null {
  const steps = quickStart(result)
  if (steps.length === 0) return null
  return section(
    TERMS.quickStart,
    2,
    numbered(steps.map((step) => `${cmd(step.command)} — ${text(step.reason)}`)),
    '_Suggested by RepoLens from the files in the repository; nothing was run._',
  )
}

function architectureIntro(result: ScanResult): string | null {
  const type = projectTypeLabel(result.project.type)
  const workspace = result.workspace
  const packages = workspace?.packages.length ?? 0
  const tools = workspace?.tools ?? []
  // Without a workspace the type alone ("Application.") repeats the overview.
  if (packages === 0 && tools.length === 0) return null
  let sentence = type ?? 'Workspace'
  if (packages > 0) sentence += ` with ${plural(packages, 'workspace package')}`
  if (tools.length > 0) {
    sentence += `, managed with ${joinWords(tools.map((tool) => `${text(tool.name)} (${code(tool.configFile)})`))}`
  }
  sentence += '.'
  const patterns = workspace?.patterns ?? []
  if (patterns.length > 0) sentence += ` Workspace patterns: ${codeList(patterns)}.`
  return sentence
}

function servicesSummary(result: ScanResult): string | null {
  const items: string[] = []
  const { services, composeFiles, dockerfiles } = result.services
  if (services.length > 0) {
    const names = services.slice(0, 12).map((service) => {
      const technology = service.technology ? ` (${text(service.technology.name)})` : ''
      return `${code(service.name)}${technology}`
    })
    const hidden = services.length - names.length
    const list = names.join(', ') + (hidden > 0 ? ` and ${hidden} more` : '')
    items.push(`Docker Compose (${codeList(composeFiles)}): ${list}.`)
  }
  if (dockerfiles.length > 0) {
    const shown = dockerfiles.slice(0, 12).map((dockerfile) => code(dockerfile.path))
    const hidden = dockerfiles.length - shown.length
    items.push(`Dockerfiles: ${shown.join(', ')}${hidden > 0 ? ` and ${hidden} more` : ''}.`)
  }
  const { databases, orms } = result.databases
  if (databases.length > 0) items.push(`Databases: ${databases.map((db) => text(db.name)).join(', ')}.`)
  if (orms.length > 0) items.push(`ORMs and query builders: ${orms.map((orm) => text(orm.name)).join(', ')}.`)
  return items.length > 0 ? bullets(items) : null
}

function architecture(result: ScanResult): string | null {
  const links = connections(result)
  return section(
    'Architecture',
    2,
    architectureIntro(result),
    section('Workspace packages', 3, packagesTable(result)),
    section(TERMS.entryPoints, 3, entrypointsList(result.project)),
    section('Top-level structure', 3, structureList(result.project)),
    section('Services and data', 3, servicesSummary(result)),
    section('How the pieces fit together', 3, links.length > 0 ? bullets(links.slice(0, 40)) : null),
  )
}

const OTHER_KINDS: readonly DependencyKind[] = ['peer', 'optional', 'indirect']

function dependencyItem(dependency: PackageDependencies['dependencies'][number]): string {
  const version = dependency.version ? ` ${inline(safeText(dependency.version))}` : ''
  const kind = dependency.kind === 'prod' ? '' : ` _(${dependency.kind})_`
  return `${code(dependency.name)}${version}${kind}`
}

function dependencies(result: ScanResult): string | null {
  const packages = result.dependencies.packages.filter((pkg) => pkg.dependencies.length > 0)
  if (packages.length === 0) return null
  const count = (pkg: PackageDependencies, kinds: readonly DependencyKind[]) =>
    formatNumber(pkg.dependencies.filter((dependency) => kinds.includes(dependency.kind)).length)
  const shown = packages.slice(0, ROW_LIMIT)
  const summary = `${plural(result.dependencies.total, 'unique direct dependency', 'unique direct dependencies')} across ${plural(packages.length, 'package')}.`
  const rows = shown.map((pkg) => [
    code(pkg.name),
    pkgRef(pkg.path),
    count(pkg, ['prod']),
    count(pkg, ['dev']),
    count(pkg, OTHER_KINDS),
  ])
  const lists = shown.map((pkg) => {
    const title = pkg.path === '.' ? `**${code(pkg.name)}** (root)` : `**${code(pkg.name)}** (${code(pkg.path)})`
    const sorted = [...pkg.dependencies].sort((a, b) => compareText(a.name, b.name))
    const items = sorted.slice(0, ROW_LIMIT).map(dependencyItem)
    return [title, bullets(items), moreLine(sorted.length - ROW_LIMIT, 'dependencies')].filter(Boolean).join('\n\n')
  })
  return section(
    'Dependencies',
    2,
    summary,
    table(['Package', 'Path', 'Prod', 'Dev', 'Other'], rows, ['left', 'left', 'right', 'right', 'right']),
    moreLine(packages.length - shown.length, 'packages'),
    details('Direct dependencies', lists.join('\n\n')),
  )
}

function services(result: ScanResult): string | null {
  const { composeFiles } = result.services
  const compose = servicesTable(result)
  return section(
    'Services',
    2,
    compose && [`Docker Compose: ${codeList(composeFiles)}.`, startServices(result)].filter(Boolean).join(' '),
    compose,
    compose && '_Ports are `host → container`; "internal" ports are only reachable from other containers._',
    section('Dockerfiles', 3, dockerfilesList(result)),
  )
}

function databases(result: ScanResult, verbose: boolean): string | null {
  const orms = ormSummary(result.databases.orms)
  return section(
    'Databases',
    2,
    databasesTable(result.databases.databases, verbose),
    orms && `ORMs and query builders: ${orms}.`,
  )
}

function environment(result: ScanResult, verbose: boolean): string | null {
  const { variables, files, usageTruncated } = result.environment
  if (variables.length === 0 && files.length === 0) return null
  return section(
    'Environment variables',
    2,
    envTable(result, { verbose }),
    variables.length > 0 && ENV_LEGEND,
    usageTruncated && '_Source scanning stopped early because of file limits; the Code column may be incomplete._',
    section('Env files', 3, envFilesList(result)),
  )
}

function scripts(result: ScanResult): string | null {
  const groups = groupScripts(result.scripts.scripts)
  const main = [...groups.root, ...groups.targets]
  const runner = result.scripts.runner
  const packages = packageScriptsTable(result)
  const packageCount = groups.packages.reduce((sum, group) => sum + group.scripts.length, 0)
  return section(
    TERMS.scripts,
    2,
    groups.root.length > 0 && runner && `Scripts in package.json run with ${cmd(runner)}.`,
    scriptsTable(main, { source: true }),
    packages && details(`Workspace package scripts (${formatNumber(packageCount)})`, packages),
  )
}

function routes(result: ScanResult): string | null {
  const { api, pages, hidden } = routeTables(result.routes.routes)
  return section(
    'Routes',
    2,
    section('API', 3, api),
    section('Pages', 3, pages),
    moreLine(hidden, 'routes'),
    result.routes.truncated && '_Route scanning stopped early because of limits; the list may be incomplete._',
  )
}

function ci(result: ScanResult): string | null {
  return section('CI', 2, ...workflowBlocks(result, 3))
}

function tooling(result: ScanResult, verbose: boolean): string | null {
  return section(TERMS.tooling, 2, ...toolingBlocks(result, 3, verbose))
}

function git(result: ScanResult): string | null {
  const { git } = result
  if (!git) return null
  const items: string[] = []
  if (git.branch) items.push(`Branch: ${code(git.branch)}`)
  else if (git.head) items.push('Detached HEAD')
  if (git.head) items.push(`HEAD: ${code(git.head)}`)
  for (const remote of [...git.remotes].sort((a, b) => compareText(a.name, b.name))) {
    items.push(`Remote ${code(remote.name)}: ${text(displayRemote(remote.url))}`)
  }
  if (git.trackedFiles !== null) items.push(`Tracked files: ${formatNumber(git.trackedFiles)}`)
  if (git.submodules.length > 0) items.push(`Submodules: ${codeList(git.submodules)}`)
  if (git.lfs) items.push('Git LFS is used (`.gitattributes`)')
  if (git.linkedWorktree) items.push('Linked worktree or submodule checkout (`.git` is a file)')
  return section('Git', 2, items.length > 0 ? bullets(items) : null)
}

function issues(result: ScanResult, verbose: boolean): string | null {
  const { diagnostics, summary, checks } = result.doctor
  const passed = `${plural(summary.passed, 'check')} passed`
  if (diagnostics.length === 0) {
    if (checks.length === 0 && summary.passed === 0) return null
    return section(TERMS.issues, 2, `No problems found. ${passed}.`)
  }
  const counts = severityParts(countSeverities(diagnostics)).join(', ')
  return section(
    TERMS.issues,
    2,
    `${counts} · ${passed}. Run ${code('repolens doctor')} for details.`,
    ...diagnosticGroups(diagnostics, 3, verbose),
  )
}

function configFiles(result: ScanResult): string | null {
  const files = [...result.configFiles].sort((a, b) => compareText(a.path, b.path))
  if (files.length === 0) return null
  const items = files.slice(0, ROW_LIMIT).map((file) => `${code(file.path)} — ${text(file.description)}`)
  const body = [bullets(items), moreLine(files.length - ROW_LIMIT, 'files')].filter(Boolean).join('\n\n')
  return section(TERMS.configFiles, 2, details(plural(files.length, 'configuration file'), body))
}

function scanNotes(result: ScanResult, verbose: boolean): string | null {
  const { truncated, files } = result.meta
  // Without --verbose, a file the issues above already call broken is not reported twice.
  const all = noteWarnings(result.meta)
  const warnings = verbose ? all : uncoveredWarnings(all, result.doctor.diagnostics)
  const items: string[] = []
  const configured = configNote(result, verbose)
  if (configured) items.push(text(configured))
  if (truncated) {
    items.push(`The scan stopped after indexing ${plural(files, 'file')}; results may be incomplete.`)
  }
  for (const warning of warnings.slice(0, ROW_LIMIT)) {
    const detail = verbose && warning.detail ? detailLine(warning.detail) : ''
    items.push(detail ? `${warningMessage(warning)}\\\n_${text(detail)}_` : warningMessage(warning))
  }
  return section(
    'Scan notes',
    2,
    items.length > 0 ? bullets(items) : null,
    moreLine(warnings.length - ROW_LIMIT, 'notes'),
  )
}

// ---------------------------------------------------------------------------
// Document
// ---------------------------------------------------------------------------

/** Markdown report used by `repolens report` and `repolens --markdown`. */
export function renderMarkdown(result: ScanResult, options: MarkdownOptions = {}): string {
  const verbose = options.verbose === true
  const version = text(result.tool.version)
  const name = projectTitle(result) ?? 'Project'
  const description = result.project.description
    ? text(truncate(safeText(result.project.description), DESCRIPTION_LIMIT))
    : null

  const sections: Block[] = [
    overview(result),
    quickStartSection(result),
    architecture(result),
    section('Languages', 2, languagesTable(result)),
    section('Frameworks', 2, frameworksTable(result, verbose)),
    dependencies(result),
    services(result),
    databases(result, verbose),
    environment(result, verbose),
    scripts(result),
    routes(result),
    ci(result),
    tooling(result, verbose),
    git(result),
    issues(result, verbose),
    configFiles(result),
    scanNotes(result, verbose),
  ]
  const hasContent = sections.some((block) => typeof block === 'string')

  // One provenance note, at the top where a reader sees it first.
  return document(
    `# ${name}`,
    description,
    `> Generated by [RepoLens](${REPOLENS_URL}) v${version} — static analysis only, no code was executed. Review before sharing.`,
    ...sections,
    !hasContent && '_RepoLens found nothing to report in this directory._',
  )
}
