import type { ScanResult } from '../types.ts'
import {
  type ContextOptions,
  renderArchitecture,
  renderCommands,
  renderContext,
  renderDevelopment,
  renderEnvironment,
  renderOverview,
  renderRoutes,
  renderServices,
} from './files.ts'

/** First line of every generated file; used to avoid overwriting files RepoLens did not create. */
export const GENERATED_MARKER = '<!-- Generated by RepoLens'

export interface AgentFile {
  /** File name inside the output directory, e.g. "overview.md". */
  name: string
  content: string
}

/** The exact first line of every generated file. */
export function generatedHeader(version: string): string {
  // The version ends up inside an HTML comment, so it must not be able to close it.
  const clean = version.replace(/[^0-9A-Za-z.+-]/g, '').replace(/-{2,}/g, '-')
  return `${GENERATED_MARKER} v${clean}. Review before committing. Regenerate with: repolens agent init -->`
}

function file(result: ScanResult, blocks: readonly string[]): string {
  return `${[generatedHeader(result.tool.version), ...blocks].join('\n\n')}\n`
}

/** Files written by `repolens agent init` into .repolens/. */
export function renderAgentFiles(result: ScanResult): AgentFile[] {
  return [
    { name: 'overview.md', content: file(result, renderOverview(result)) },
    { name: 'architecture.md', content: file(result, renderArchitecture(result)) },
    { name: 'commands.md', content: file(result, renderCommands(result)) },
    { name: 'environment.md', content: file(result, renderEnvironment(result)) },
    { name: 'services.md', content: file(result, renderServices(result)) },
    { name: 'routes.md', content: file(result, renderRoutes(result)) },
    { name: 'development.md', content: file(result, renderDevelopment(result)) },
    { name: 'agent-context.md', content: renderAgentContext(result) },
  ]
}

/**
 * Single concise context document: `agent-context.md`, and what `repolens agent`
 * prints (with `companionFiles: false`, since the other files don't exist then).
 */
export function renderAgentContext(result: ScanResult, options: ContextOptions = {}): string {
  return file(result, renderContext(result, options))
}
