/** The package entry point (`import { scan } from 'repolens-cli'`), as programmatic users see it. */
import { describe, expect, it } from 'vitest'
import type { AgentFile, ContextOptions, MarkdownOptions, RenderOptions, Style } from '../../src/index.ts'
import * as api from '../../src/index.ts'
import { renderDoctor as fullRenderDoctor, renderScan as fullRenderScan } from '../../src/output/terminal.ts'
import { sampleScanResult } from '../factories.ts'

describe('public API', () => {
  it('exports the entry points and the option types they take', () => {
    for (const name of ['scan', 'renderScan', 'renderDoctor', 'renderMarkdown', 'renderAgentContext', 'createStyle']) {
      expect(typeof (api as Record<string, unknown>)[name]).toBe('function')
    }
    const style: Style = api.createStyle({ color: false, unicode: false })
    const options: RenderOptions = api.defaultRenderOptions({ style })
    const markdown: MarkdownOptions = { verbose: true }
    const context: ContextOptions = { companionFiles: false }
    const files: AgentFile[] = api.renderAgentFiles(sampleScanResult())
    expect(options.style.symbols.pass).toBe('+')
    expect(api.renderMarkdown(sampleScanResult(), markdown)).toContain('#')
    expect(api.renderAgentContext(sampleScanResult(), context)).toContain('Generated by RepoLens')
    expect(files.map((file) => file.name)).toContain('agent-context.md')
  })

  it('renderScan and renderDoctor accept partial options and default the rest', () => {
    const result = sampleScanResult()
    expect(api.renderScan(result)).toBe(fullRenderScan(result, api.defaultRenderOptions()))
    expect(api.renderDoctor(result, { width: 60 })).toBe(
      fullRenderDoctor(result, api.defaultRenderOptions({ width: 60 })),
    )
    // An explicit undefined (an unset optional value passed through) keeps the default.
    expect(api.renderScan(result, { width: undefined, style: undefined })).toBe(api.renderScan(result))
    const ascii = api.renderDoctor(result, { style: api.createStyle({ color: false, unicode: false }) })
    expect(ascii).toBe(
      fullRenderDoctor(result, api.defaultRenderOptions({ style: api.createStyle({ color: false, unicode: false }) })),
    )
  })
})
